name: Build

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches: [ "master" ]
  pull_request:
    types: [ opened, synchronize, ready_for_review ]

concurrency:
  # New commit on master branch cancels currently running workflows of this branch
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        os: [ "alt:p10", "alt:p11" ]
      fail-fast: false
    uses: ./.github/workflows/build.yml
    with:
      os: ${{ matrix.os }}
    secrets: inherit

